/*
 * M2Factor
 *
 * This file was automatically generated for 2Factor by APIMATIC BETA v2.0 on 02/18/2016
 */
package SolvTech.models;

import java.util.*;

public class SendingVoiceOtpAutoGeneratedOtpModelBuilder {
    //the instance to build
    private SendingVoiceOtpAutoGeneratedOtpModel sendingVoiceOtpAutoGeneratedOtpModel;

    /**
     * Default constructor to initialize the instance
     */
    public SendingVoiceOtpAutoGeneratedOtpModelBuilder() {
        sendingVoiceOtpAutoGeneratedOtpModel = new SendingVoiceOtpAutoGeneratedOtpModel();
    }

    public SendingVoiceOtpAutoGeneratedOtpModelBuilder details(String details) {
        sendingVoiceOtpAutoGeneratedOtpModel.setDetails(details);
        return this;
    }

    public SendingVoiceOtpAutoGeneratedOtpModelBuilder status(String status) {
        sendingVoiceOtpAutoGeneratedOtpModel.setStatus(status);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SendingVoiceOtpAutoGeneratedOtpModel build() {
        return sendingVoiceOtpAutoGeneratedOtpModel;
    }
}