/*
 * M2Factor
 *
 * This file was automatically generated for 2Factor by APIMATIC BETA v2.0 on 02/18/2016
 */
package SolvTech.models;

import java.util.*;

public class SendingSmsOtpAutoGeneratedOtpModelBuilder {
    //the instance to build
    private SendingSmsOtpAutoGeneratedOtpModel sendingSmsOtpAutoGeneratedOtpModel;

    /**
     * Default constructor to initialize the instance
     */
    public SendingSmsOtpAutoGeneratedOtpModelBuilder() {
        sendingSmsOtpAutoGeneratedOtpModel = new SendingSmsOtpAutoGeneratedOtpModel();
    }

    public SendingSmsOtpAutoGeneratedOtpModelBuilder details(String details) {
        sendingSmsOtpAutoGeneratedOtpModel.setDetails(details);
        return this;
    }

    public SendingSmsOtpAutoGeneratedOtpModelBuilder status(String status) {
        sendingSmsOtpAutoGeneratedOtpModel.setStatus(status);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SendingSmsOtpAutoGeneratedOtpModel build() {
        return sendingSmsOtpAutoGeneratedOtpModel;
    }
}